// <auto-generated />
namespace MoodDiaryProjectW2024.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class diaries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diaries));
        
        string IMigrationMetadata.Id
        {
            get { return "202402072132126_diaries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
